export const items = [
  {
    name: "GraphQL Crash Course in 2024 | Build a Full Stack MERN App",
    category: "Web Development",
    youtubeChannel: "As a Programmer",
    lengthInHours: 4.5,
    techStack: [
      "MERN",
      "MongoDB",
      "Express.js",
      "React.js",
      "Node.js",
      "Apollo GraphQL",
    ],
    difficulty: "Intermediate",
    link: "https://www.youtube.com/watch?v=Vr-QHtbmd38",
  },
  {
    name: "How To Build a Netflix Clone with MERN Stack in 2024 - Full Course",
    category: "Web Development",
    youtubeChannel: "As a Programmer",
    lengthInHours: 7,
    techStack: ["React.js", "Node.js", "Express.js", "MongoDB", "Tailwind"],
    difficulty: "Intermediate",
    link: "https://www.youtube.com/watch?v=gRroBZczKAU",
  },
  {
    name: "Portfolio Website",
    category: "Web Development",
    youtubeChannel: "CodeWithHarry",
    lengthInHours: 3,
    techStack: ["React", "Tailwind CSS", "typescript"],
    difficulty: "Beginner",
  },
  {
    name: "Fitness Tracker",
    category: "Mobile Development",
    youtubeChannel: "The Net Ninja",
    lengthInHours: 6,
    techStack: ["React Native", "Firebase", "python"],
    difficulty: "Advanced",
  },
  {
    name: "Task Manager",
    category: "Web Development",
    youtubeChannel: "FreeCodeCamp",
    lengthInHours: 4,
    techStack: ["Vue.js", "Node.js"],
    difficulty: "Intermediate",
  },
  {
    name: "Stock Market Dashboard",
    category: "Data Analysis",
    youtubeChannel: "Tech With Tim",
    lengthInHours: 7,
    techStack: ["Python", "Flask", "Matplotlib"],
    difficulty: "Advanced",
  },
  {
    name: "Stock Market Dashboard",
    category: "Data Analysis",
    youtubeChannel: "Tech With Tim",
    lengthInHours: 7,
    techStack: ["Python", "Flask", "Matplotlib"],
    difficulty: "Advanced",
  },
  {
    name: "Stock Market Dashboard",
    category: "Data Analysis",
    youtubeChannel: "Tech With Tim",
    lengthInHours: 7,
    techStack: ["Python", "Flask", "Matplotlib"],
    difficulty: "Advanced",
  },
  {
    name: "Stock Market Dashboard",
    category: "Data Analysis",
    youtubeChannel: "Tech With Tim",
    lengthInHours: 7,
    techStack: ["Python", "Flask", "Matplotlib"],
    difficulty: "Advanced",
  },
  {
    name: "Stock Market Dashboard",
    category: "Data Analysis",
    youtubeChannel: "Tech With Tim",
    lengthInHours: 7,
    techStack: ["Python", "Flask", "Matplotlib"],
    difficulty: "Advanced",
  },
  {
    name: "Stock Market Dashboard",
    category: "Data Analysis",
    youtubeChannel: "Tech With Tim",
    lengthInHours: 7,
    techStack: ["Python", "Flask", "Matplotlib"],
    difficulty: "Advanced",
  },
  {
    name: "Stock Market Dashboard",
    category: "Data Analysis",
    youtubeChannel: "Tech With Tim",
    lengthInHours: 7,
    techStack: ["Python", "Flask", "Matplotlib"],
    difficulty: "Advanced",
  },
  {
    name: "Stock Market Dashboard",
    category: "Data Analysis",
    youtubeChannel: "Tech With Tim",
    lengthInHours: 7,
    techStack: ["Python", "Flask", "Matplotlib"],
    difficulty: "Advanced",
  },
  {
    name: "Stock Market Dashboard",
    category: "Data Analysis",
    youtubeChannel: "Tech With Tim",
    lengthInHours: 7,
    techStack: ["Python", "Flask", "Matplotlib"],
    difficulty: "Advanced",
  },
  {
    name: "Stock Market Dashboard",
    category: "Data Analysis",
    youtubeChannel: "Tech With Tim",
    lengthInHours: 7,
    techStack: ["Python", "Flask", "Matplotlib"],
    difficulty: "Advanced",
  },
  {
    name: "Stock Market Dashboard",
    category: "Data Analysis",
    youtubeChannel: "Tech With Tim",
    lengthInHours: 7,
    techStack: ["Python", "Flask", "Matplotlib"],
    difficulty: "Advanced",
  },
];
